### ISSUE TITLE
Article Query, Argument must be an instance of ArticleDetail, array given

### ISSUE THREAD

**Issue by geekazoid-at** [LeadCommerceDE/shopware-sdk#19]
Hi, I am taking my first steps with the shopware-sdk.
I managed to get auth working, however when doing `$this->shopwareClient->getArticleQuery()->findOne(1)`, I get the following error:

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to LeadCommerce\Shopware\SDK\Entity\Article::setMainDetail() must be an instance of LeadCommerce\Shopware\SDK\Entity\ArticleDetail, array given, called in /var/www/shopware/custom/plugins/HabuAVS/Components/vendor/leadcommerce/shopware-sdk/src/LeadCommerce/Shopware/SDK/Entity/Base.php on line 34 and defined in /var/www/shopware/custom/plugins/HabuAVS/Components/vendor/leadcommerce/shopware-sdk/src/LeadCommerce/Shopware/SDK/Entity/Article.php:681
Stack trace:
#0 /var/www/shopware/custom/plugins/HabuAVS/Components/vendor/leadcommerce/shopware-sdk/src/LeadCommerce/Shopware/SDK/Entity/Base.php(34): LeadCommerce\Shopware\SDK\Entity\Article->setMainDetail(Array)
#1 /var/www/shopware/custom/plugins/HabuAVS/Components/vendor/leadcommerce/shopware-sdk/src/LeadCommerce/Shopware/SDK/Query/Base.php(139): LeadCommerce\Shopware\SDK\Entity\Base->setEntityAttributes(Array)
#2 /var/www/shopware/custom/plugins/HabuAVS/Components/vendor/leadcommerce/shopware-sdk/src/LeadCommerce/Shopware/SD in /var/www/shopware/custom/plugins/HabuAVS/Components/vendor/leadcommerce/shopware-sdk/src/LeadCommerce/Shopware/SDK/Entity/Article.php on line 681`

The value itself gives me the following when passed to print_r()

`Array
(
    [id] => 1
    [articleId] => 1
    [unitId] =>
    [number] => 3417491
    [supplierNumber] =>
    [kind] => 1
    [additionalText] =>
    [active] => 1
    [inStock] => 0
    [stockMin] => 0
    [lastStock] =>
    [weight] => 0.000
    [width] =>
    [len] =>
    [height] =>
    [ean] =>
    [purchasePrice] => 0
    [position] => 0
    [minPurchase] => 1
    [purchaseSteps] =>
    [maxPurchase] => 0
    [purchaseUnit] =>
    [referenceUnit] =>
    [packUnit] =>
    [shippingFree] =>
    [releaseDate] =>
    [shippingTime] =>
    [prices] => Array
        (
            [0] => Array
                (
                    [id] => 1
                    [articleId] => 1
                    [articleDetailsId] => 1
                    [customerGroupKey] => EK
                    [from] => 1
                    [to] => beliebig
                    [price] => 14.090909090909
                    [pseudoPrice] => 0
                    [percent] => 0
                    [customerGroup] => Array
                        (
                            [id] => 1
                            [key] => EK
                            [name] => Shopkunden
                            [tax] => 1
                            [taxInput] => 1
                            [mode] =>
                            [discount] => 0
                            [minimumOrder] => 0
                            [minimumOrderSurcharge] => 0
                        )

                )

        )

    [attribute] => Array
        (
            [id] => 1
            [articleId] => 1
            [articleDetailId] => 1
            [attr1] =>
            [attr2] =>
            [attr3] =>
            [attr4] =>
            [attr5] =>
            [attr6] =>
            [attr7] =>
            [attr8] =>
            [attr9] =>
            [attr10] =>
            [attr11] =>
            [attr12] =>
            [attr13] =>
            [attr14] =>
            [attr15] =>
            [attr16] =>
            [attr17] =>
            [attr18] =>
            [attr19] =>
            [attr20] =>
            [articleAnwendung] =>
            [articleHinweise] =>
            [articleInhaltsstoffe] =>
            [articlePackungsinhalt] => 200 ML
            [articleArtikelnummer] =>
            [articleSerie] => 5357
            [articleMediNebenwirkung] =>
            [articleMediAnwendung] =>
            [articleMediEinnahmeBeachten] =>
            [articleMediEinnahmeWie] =>
            [articleMediAufbewahrung] =>
            [articleMediInhalt] =>
            [articleMediAlkohol] => 0
            [articleAvp] =>
            [articleMedWirkstoff] =>
            [articleMedZulassungsnummer] =>
            [articleDarreichungsform] => 646
        )

    [configuratorOptions] => Array
        (
        )

)
1`

We are currently testing this on Shopware 5.5.3.
What am I doing wrong? I could not find something about this problem, so I am posting here.

Thank you, kind regards!

**Comment by aWuttig** [comment]
Hey, 

this is because of a bug in the setEntityAttributes method.

https://github.com/LeadCommerceDE/shopware-sdk/blob/db2bfcbb8fa73746b3efe87e63e1103c804b8e3a/src/LeadCommerce/Shopware/SDK/Entity/Base.php

If the result from shopware API is nested the value in $this->$setter($value); will be an array instead of the entity.

I try to find a solution for this.

**Comment by swigle** [comment]
I've got the same error on 5.5.7.
Any news on this? Without it, the SDK is not usable i'm afraid

**Comment by swigle** [comment]
As a **very quick and dirty fix** i've added the following code to SDK/Entity/Article.php Article class:
`public function setEntityAttributes(array $attributes)
    {
        foreach ($attributes as $attribute => $value) {
            $setter = 'set' . ucfirst($attribute);

            if($setter == 'setMainDetail' && is_array($value)) {
                $this->handleArticleDetail($value);
            }
            else if (method_exists($this, $setter)) {
                $this->$setter($value);
            }
        }

        return $this;
    }

    private function handleArticleDetail($attributes) {
        $detail = new ArticleDetail();
        foreach ($attributes as $attribute => $value) {
            $setter = 'set' . ucfirst($attribute);
            if (method_exists($detail, $setter)) {
                $detail->$setter($value);
            }
        }
        $detail->setArticleId($this->getId());
        $this->setMainDetail($detail);
    }`

I've overridden the setEntityAttributes() function for articles so that it checks for the sub arrays and handles them correctly.

_Disclaimer_: Yes this is dirty, and not a permanent sollution. I would advice against using this, but at least i can continue testing now :)
